name = "c-45177-vip"
main = "index.js"
compatibility_date = "2024-01-01"

# KV 命名空间 (API mock 数据 - 所有站点共享)
[[kv_namespaces]]
binding = "KV"
id = "a7cc6d7a39764a05a5fe46f56233ca7d"

[[d1_databases]]
binding = "DB"
database_name = "clone-api-db"
database_id = "077de9d1-9a3d-4f12-85d6-477fef7e21b7"

# R2 存储桶 (静态资源 - 所有站点共享)
[[r2_buckets]]
binding = "R2"
bucket_name = "clone-sites"
